# Generated by Django 6.0.7 on 2026-07-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='adoption_status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('D', 'Adopted')], default='A', max_length=1),
        ),
    ]
