# Generated by Django 6.0.7 on 2026-07-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_adoptionmodel_pet_delete_pets_adoptionmodel_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptionmodel',
            name='adopter_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='adoptionmodel',
            name='adopter_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='adoption_status',
            field=models.CharField(choices=[('A', 'Available'), ('P', 'Pending'), ('D', 'Adopted')], default='A', max_length=1),
        ),
    ]
